boot0: Add A133 DRAM parameter support and DRAM.ext support
apritzel/sunxi-fw pull request #6
Opened 2024-10-22 05:26 UTC by BrokenR3C0RD

This was tested using the PhoenixSuite recovery image for the Creality Sonic Pad. Adding the initial DRAM parameter support did not display the expected parameters; after further investigation I discovered the existence of the extended header. This may be present on boot0 images besides the A133, so I made it a generalized feature. These are also stored in the `sys_config.fex` as `[dram_para%d]`

Along with this is some small typo fixes in the para_names array and a refactor of the DRAM parameters prints to move it into another function, so it can be used in the DRAM.ext output code.

<details>
<summary>Output from <code>sunxi-fw info -v</code> on my device's boot0 with these changes</summary>

```
@   0: boot0: Allwinner boot0
        size: 65536 bytes
        eGON checksum matches: 0x6aaf5251
        DRAM parameters:              A64        H616        A133          H6
                DRAM clock  :       0x2d0       0x2d0       0x2d0           -
                DRAM type   :         0x3         0x3         0x3           -
                ZQ value    :   0x7070707           -           -           -
                ODT enabled :   0xc0c0c0c  0x15101212           -           -
                DX ODT      :           -   0x7070707   0x7070707           -
                DX DRI      :           -   0xc0c0c0c   0xc0c0c0c           -
                CA DRI      :           -       0xe0e       0xe0e           -
                PARA0       :           -           -  0x15101212           -
                PARA1       :       0xe0e      0x30fa      0x30fa           -
                PARA2       :  0x15101212           0           0           -
                MR0         :      0x30fa       0x840       0x840           -
                MR1         :           0         0x4         0x4           -
                MR2         :       0x840         0x8         0x8           -
                MR3         :         0x4           0           0           -
                TPR0        :         0x8           0           0           -
                TPR6        :           0  0x33808080  0x33808080           -
                TPR10       :           0    0x2f7458    0x2f7458           -
                TPR11       :           0   0xf0b0e0c   0xf0b0e0c           -
                TPR12       :           0  0x19191818  0x19191818           -
                TPR13       :           0        0x40        0x40           -
                TPR14       :           -           -  0x26232323           -
        DRAM parameters 3:            A64        H616        A133          H6
                DRAM clock  :       0x2d0       0x2d0       0x2d0           -
                DRAM type   :         0x4         0x4         0x4           -
                ZQ value    :   0x3030303           -           -           -
                ODT enabled :   0xc0c0c0c  0x12131615           -           -
                DX ODT      :           -   0x3030303   0x3030303           -
                DX DRI      :           -   0xc0c0c0c   0xc0c0c0c           -
                CA DRI      :           -      0x1919      0x1919           -
                PARA0       :           -           -  0x12131615           -
                PARA1       :      0x1919      0x60fa      0x60fa           -
                PARA2       :  0x12131615           0           0           -
                MR0         :      0x60fa       0x840       0x840           -
                MR1         :           0       0x601       0x601           -
                MR2         :       0x840         0x8         0x8           -
                MR3         :       0x601           0           0           -
                MR5         :           -       0x400       0x400           -
                MR6         :           -       0x862       0x862           -
                TPR0        :         0x8           0           0           -
                TPR3        :       0x400           0           0           -
                TPR4        :       0x862           -           0           -
                TPR6        :           0      0xa000      0xa000           -
                TPR10       :           0    0x2f7777    0x2f7777           -
                TPR11       :           0   0xf101511   0xf101511           -
                TPR12       :           0   0xf0f1512   0xf0f1512           -
                TPR13       :           0      0x1d00      0x1d00           -
                TPR14       :           -           -  0x19191c1c           -
        DRAM parameters 7:            A64        H616        A133          H6
                DRAM clock  :       0x2d0       0x2d0       0x2d0           -
                DRAM type   :         0x3         0x3         0x3           -
                ZQ value    :   0x7070707           -           -           -
                ODT enabled :   0xc0c0c0c  0x15101212           -           -
                DX ODT      :           -   0x7070707   0x7070707           -
                DX DRI      :           -   0xc0c0c0c   0xc0c0c0c           -
                CA DRI      :           -       0xe0e       0xe0e           -
                PARA0       :           -           -  0x15101212           -
                PARA1       :       0xe0e      0x30fa      0x30fa           -
                PARA2       :  0x15101212           0           0           -
                MR0         :      0x30fa       0x840       0x840           -
                MR1         :           0         0x4         0x4           -
                MR2         :       0x840         0x8         0x8           -
                MR3         :         0x4           0           0           -
                TPR0        :         0x8           0           0           -
                TPR6        :           0  0x33808080  0x33808080           -
                TPR10       :           0    0x2f7458    0x2f7458           -
                TPR11       :           0   0xf0b0e0c   0xf0b0e0c           -
                TPR12       :           0  0x19191818  0x19191818           -
                TPR13       :           0        0x40        0x40           -
                TPR14       :           -           -  0x26232323           -
```

</details>

2024-10-28 13:42 UTC, apritzel approved these changes

2024-10-28 13:59 UTC, apritzel approved these changes
I cannot really verify that, but it looks good to me, and it certainly seems to produce some sensible output.

2024-10-28 14:40 UTC, apritzel requested changes

2024-10-28 14:40 UTC, apritzel commented on sunxi-boot0.c
> +	[SOC_H6] = "H6",
Can you please remove the H6 entry here, and in the enum above? There is little point in putting it there, and it might break 80 columns, making the output harder to read on a normal terminal.

2024-10-28 14:40 UTC, apritzel commented on sunxi-boot0.c
> +void output_boot0_dram_para(const uint32_t *para, FILE *stream, char const* indent)
what's the purpose of the indent parameter, exactly? Even when looking at the next patch, I only ever see "\t" passed in here, so why the flexibility?
In general the output seems to off by one tab? (headers don't align correctly, and there is a "2 tabs" gap at the beginning?

2024-10-28 14:40 UTC, apritzel commented on sunxi-boot0.c
> +	uint32_t i;
Please use a normal "int" for the type here, it's nothing hardware specific.

2024-10-28 14:40 UTC, apritzel commented on sunxi-boot0.c
> +#define OFS(x) ((x) + 1)
Please add a comment stating the purpose of "+ 1" here. I guess it's to differentiate it from the special zero case?

2024-10-28 14:40 UTC, apritzel commented on sunxi-boot0.c
> +		fprintf(stream, "%s\t\t%-12s:", indent, param_name[i]);
I think here it's one tab too many. Either you ditch the idea of "indent" here, or just have one tab afterwards.

2024-10-28 14:42 UTC, apritzel requested changes

2024-10-28 14:42 UTC, apritzel commented on sunxi-boot0.c
> +
stray line

2024-10-28 14:42 UTC, apritzel commented on sunxi-boot0.c
> +	uint32_t i, ofs;
please have an empty line after the variable declaration

2024-11-24 00:23 UTC, BrokenR3C0RD commented on sunxi-boot0.c
> +void output_boot0_dram_para(const uint32_t *para, FILE *stream, char const* indent)
This was a leftover because I was originally intending to format the dram_para_ext output differently, and forgot to remove it. Will fix

2025-04-22 00:07 UTC, apritzel commented
I fixed the few nits I mentioned, and adjusted the code split slightly. Now merged.

2025-04-22 00:07 UTC, closed without merging